### ISSUE TITLE
How to run the program

### ISSUE THREAD

**Issue by KPFC** [gregordick/divinum-officium-alterum#4]
I found you started this project and I find the general concept very good, but after cloning it and trying to run it I could not figure out how it works. I thought I'd have to run 
`scripts/bringup-datagen.py` or `scripts/bringup.py` but apparently a datafile is required of which I have no clue how its structure should be. So I thought instead of trying to figure this out for hours I'll just ask:

How do you run this program and if you use some placeholder datafiles, it would be nice if you could publish it here as well.

**Comment by gregordick** [comment]
Thanks for your interest.  I've added a demo script and a [GH action](https://github.com/gregordick/divinum-officium-alterum/actions/workflows/bringup-demo.yml) to run it.  One of the aims of this project is to keep the data separate from the code, so I don't plan to commit datafiles to this repo, but the demo script generates data for consumption by this package (in an emphatically non-final and unstable format) from Divinum Officium's data, and then generates Vespers for one date.
